export const wordsL6 = [
  "atomic",
  "appeal",
  "belief",
  "burden",
  "combat",
  "covers",
  "doctor",
  "design",
  "editor",
  "engine",
  "fabric",
  "famous",
  "gather",
  "honest",
  "health",
  "indeed",
  "invest",
  "jersey",
  "junior",
  "killed",
  "legacy",
  "liquid",
  "margin",
  "module",
  "native",
  "normal",
  "patent",
  "player",
  "rating",
  "remote",
  "speech",
  "spirit",
  "talent",
  "tennis",
  "unique",
  "update",
  "victim",
  "winter",
  "yellow",
];

export const wordsL7 = [
  "ability",
  "advance",
  "bedroom",
  "brother",
  "century",
  "chicken",
  "density",
  "display",
  "economy",
  "extreme",
  "failure",
  "fashion",
  "gateway",
  "heavily",
  "holiday",
  "imagine",
  "insight",
  "journey",
  "justice",
  "kingdom",
  "kitchen",
  "liberal",
  "loyalty",
  "machine",
  "million",
  "nuclear",
  "opinion",
  "outlook",
  "passive",
  "plastic",
  "quality",
  "quarter",
  "radical",
  "rollout",
  "science",
  "special",
  "therapy",
  "traffic",
  "unusual",
  "upgrade",
  "variety",
  "victory",
  "western",
  "writing",
];

export const normalBoardDefault = [
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
];

export const hardBoardDefault = [
  ['', '', '', '', '', '', ''],
  ['', '', '', '', '', '', ''],
  ['', '', '', '', '', '', ''],
  ['', '', '', '', '', '', ''],
  ['', '', '', '', '', '', ''],
];
